//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electric {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    public sealed partial class ElectSet : global::System.Configuration.ApplicationSettingsBase {
        
        private static ElectSet defaultInstance = ((ElectSet)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ElectSet())));
        
        public static ElectSet Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24小时之内工作自动发货亲\r\n")]
        public string 开始回复 {
            get {
                return ((string)(this["开始回复"]));
            }
            set {
                this["开始回复"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("亲，需要什么商品直接下单，机器人自动发货")]
        public string 结束回复 {
            get {
                return ((string)(this["结束回复"]));
            }
            set {
                this["结束回复"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("谢谢惠顾亲。")]
        public string 订单回复 {
            get {
                return ((string)(this["订单回复"]));
            }
            set {
                this["订单回复"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string uid位数 {
            get {
                return ((string)(this["uid位数"]));
            }
            set {
                this["uid位数"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 默认订单表格 {
            get {
                return ((string)(this["默认订单表格"]));
            }
            set {
                this["默认订单表格"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 默认商品表格 {
            get {
                return ((string)(this["默认商品表格"]));
            }
            set {
                this["默认商品表格"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("asd")]
        public string 默认管理员账号 {
            get {
                return ((string)(this["默认管理员账号"]));
            }
            set {
                this["默认管理员账号"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123456")]
        public string 默认管理员密码 {
            get {
                return ((string)(this["默认管理员密码"]));
            }
            set {
                this["默认管理员密码"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 默认财务表格 {
            get {
                return ((string)(this["默认财务表格"]));
            }
            set {
                this["默认财务表格"] = value;
            }
        }
    }
}
